import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		
        Random generator = new Random(seed);  

        double totalChildren = 0;
        int familiesWith2Children = 0;
        int familiesWith3Children = 0;
        int familiesWith4OrMoreChildren = 0;

        for (int i = 0; i < T; i++) {
            
				boolean boyBorn = false;
				boolean girlBorn = false;
				int childrenCount = 0;
		
				while (!(boyBorn && girlBorn)) {
					// Generate a random value (0 or 1) to represent the gender
					double gender = generator.nextDouble();; // 0 for girl, 1 for boy
		
					// Update the Boolean variables based on the gender
					if (gender <0.5) {
						girlBorn = true;
					} else {
						boyBorn = true;
					}
		
					// Print the gender (g for girl, b for boy)
					// System.out.print((gender == 0) ? "g " : "b ");
		
					// Increment the count of children
					childrenCount++;

                    totalChildren++;
				}

                if(childrenCount==2){
                    familiesWith2Children++;
                }
                if(childrenCount==3){
                    familiesWith3Children++;
                }
                if(childrenCount>3){
                    familiesWith4OrMoreChildren++;
                }

            }
                double x = totalChildren /T;
                System.out.println("Average: " + x + " children to get at least one of each gender.");
                System.out.println("Number of families with 2 children: " + familiesWith2Children);
                System.out.println("Number of families with 3 children: " + familiesWith3Children);
                System.out.println("Number of families with 4 or more children: " + familiesWith4OrMoreChildren);
				if(familiesWith2Children >familiesWith3Children && familiesWith2Children >familiesWith4OrMoreChildren )
				{
					System.out.println("The most common number of children is 2.");
				}
		
			if(familiesWith3Children >familiesWith2Children && familiesWith3Children >familiesWith4OrMoreChildren )
				{
					System.out.println("The most common number of children is 3.");
				}
				if(familiesWith4OrMoreChildren >familiesWith2Children &&  familiesWith4OrMoreChildren >familiesWith2Children )
				{
					System.out.println("The most common number of children is 4 or more.");
				}
		}


		    
	}

